services:
  etcdfinder-ui:
    image: ghcr.io/etcdfinder/etcdfinder-ui:latest
    pull_policy: always
    container_name: etcdfinder-ui
    ports:
      - "3000:3000"
    networks:
      - etcdfinder-net
    environment:
      BACKEND_URL: http://etcdfinder:8080
    restart: unless-stopped
    depends_on:
      - etcdfinder
  etcdfinder:
    image: ghcr.io/etcdfinder/etcdfinder:latest
    pull_policy: always
    container_name: etcdfinder
    expose:
      - "8080"
    networks:
      - etcdfinder-net
    environment:
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS:?Please set ETCD_ENDPOINTS environment variable or use the quickstart deployment (cd ../quickstart && docker-compose up)}
      DATASTORE_MEILISEARCH_HOST: http://meilisearch:7700
    restart: unless-stopped
    depends_on:
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    pull_policy: always
    container_name: meilisearch
    expose:
      - "7700"
    networks:
      - etcdfinder-net
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch_data:/var/lib/meilisearch
    restart: unless-stopped
    
networks:
  etcdfinder-net:
    driver: bridge

volumes:
  meilisearch_data:
