

services:
  etcdfinder-ui:
    image: ghcr.io/etcdfinder/etcdfinder-ui:latest
    pull_policy: always
    container_name: etcdfinder-ui
    ports:
      - "3000:3000"
    networks:
      - etcdfinder-net
    environment:
      BACKEND_URL: http://etcdfinder:8080
    restart: unless-stopped
    depends_on:
      - etcdfinder
  etcdfinder:
    image: ghcr.io/etcdfinder/etcdfinder:latest 
    pull_policy: always
    container_name: etcdfinder
    expose:
      - "8080"
    networks:
      - etcdfinder-net
    environment:
      ETCD_ENDPOINTS: http://etcd:2379
      DATASTORE_MEILISEARCH_HOST: http://meilisearch:7700
    restart: unless-stopped
    depends_on:
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    pull_policy: always
    container_name: meilisearch
    expose:
      - "7700"
    networks:
      - etcdfinder-net
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meilisearch_data:/var/lib/meilisearch
    restart: unless-stopped
  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    pull_policy: always
    container_name: etcd
    expose:
      - "2379"
    networks:
      - etcdfinder-net
    environment:
      ETCD_NAME: etcd
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - etcd_data:/etcd-data
    restart: unless-stopped
    
networks:
  etcdfinder-net:
    driver: bridge

volumes:
  meilisearch_data:
  etcd_data:
