server:
  port: 8080
log:
  level: info
etcd:
  version: v3
  endpoints: http://localhost:22379
  root_etcd_prefix: ""
  watch_event_channel_size: 100
  pagination_limit: 10000
  etcd_audit_period: 60
  max_watch_retries: 5
datastore:
  type: meilisearch
  meilisearch:
    host: http://localhost:7700
    index_name: etcd-keys
    matching_strategy: frequency
